### Cek Ongkir JNE
POST https://rajaongkir.komerce.id/api/v1/calculate/domestic-cost
Content-Type: application/x-www-form-urlencoded
Accept: application/json
key:  Of5uxI7I5f0e87761b137545zMw6Ka4U

origin=64999&destination=64942&weight=1000&courier=jne